# native package workflows
name: build and publish release
on: [push]

env:
  CATCODE2_RELEASE: false
  CATCODE2_CI: true
  GRADLE_OPTS: "-Xmx8G -XX:MaxPermSize=2G -Dfile.encoding=UTF-8"
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


jobs:
  publish-npm:
    name: Publish to npm
#    strategy:
#      matrix:
#        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Check out repo
        uses: actions/checkout@v2

      # Setup java
      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'


      - name: Gradle Publish To Npm
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: publishToNpm


