name: test
on: push
env:
  GRADLE_OPTS: "-Xmx8G -XX:MaxPermSize=2G -Dfile.encoding=UTF-8 -DA=B"

jobs:
  test:
    name: Just test
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          # release workflow should have access to all tags
          fetch-depth: 0

      # Setup java
      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Test gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: justtest